### ISSUE TITLE
Week ToDo List

### ISSUE THREAD

**Issue by kipkurui** [mbbu/HPC_ToDo#15]
@- [x] Instal RStudio
- [x] Install JupyterHub
- [x] Setup ansible
- [x] Deploy galxy
- [x] create work template module for getting started with galaxy on hpc
- [x] review user  and data management policy for hpc and publish the final document
- [x] finalize on module set up
- [x] Mount new server 
- [x] Assign IP address,server name and configure dhcp
- [x] Install operating system
- [x] set up high availability cluster with two nodes
- [x] finalize on module set up
- [x] Dokuwiki set up
- [x] Server Documentation
- [x] Set Centralized authentication management
- [x] Galaxy configuration
- [x] Application public access review

**Comment by espirado** [comment]
Moving towards using weekly task monitor
